Port 3128
Listen 0.0.0.0
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogLevel Info
MaxClients 64
DisableViaHeader Yes
Allow 0.0.0.0/0
ConnectPort 80
ConnectPort 443
ConnectPort 8443
